workflows:
  build-alrc-tv:
    name: Build ALRC TV APK
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      #android_signing:
        #keystore_reference: ALRC_TV_KEYSTORE
      vars:
        PACKAGE_NAME: "com.alrcmedia.alrctv"
    scripts:
      - name: 🧠 Augmenter la mémoire Java
        script: echo "org.gradle.jvmargs=-Xmx4096m" >> android/gradle.properties
      
      - name: 🧼 Nettoyage
        script: flutter clean

      - name: 📦 Install dependencies
        script: |
          flutter pub get

      - name: 🛠️ Build APK
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

    publishing:
      email:
        recipients:
          - groupealrc@gmail.com
